# Generated by Django 2.0.6 on 2018-06-12 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('payment_date', models.DateTimeField(blank=True, db_index=True)),
                ('token_expiry_date', models.DateTimeField(blank=True)),
                ('is_tokenized', models.BooleanField(db_index=True, default=False)),
                ('is_token_expired', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_void', models.BooleanField(db_index=True, default=False)),
                ('payment_status', models.TextField(blank=True)),
                ('payment_token', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
    ]
