# Generated by Django 2.0.6 on 2018-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_auto_20180612_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='token_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
