# Generated by Django 2.0.6 on 2018-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_auto_20180721_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
