# Generated by Django 2.0.6 on 2018-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_purchaseorder_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.IntegerField(help_text='Diskon Member', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.IntegerField(help_text='Ongkos Kirim', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_payment',
            field=models.IntegerField(help_text='Total Belanja', null=True),
        ),
    ]
