# Generated by Django 2.0.6 on 2018-08-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_auto_20180809_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='purchases_order',
            new_name='purchase_order',
        ),
    ]
