# Generated by Django 2.0.6 on 2018-08-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_auto_20180809_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_token_expired',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_tokenized',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_token',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='token_expiry_date',
        ),
    ]
