# Generated by Django 2.0.6 on 2018-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_auto_20180809_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_price',
            field=models.IntegerField(help_text='Total Belanja', null=True),
        ),
    ]
