# Generated by Django 2.0.6 on 2018-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0011_purchaseorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='alamat_tujuan',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
