# Generated by Django 2.0.6 on 2018-08-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_auto_20180809_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_void',
        ),
    ]
