# Generated by Django 2.0.6 on 2018-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0013_remove_purchaseorder_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_checked_out',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
