# Generated by Django 2.0.6 on 2018-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0014_purchaseorder_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
