# Generated by Django 2.0.6 on 2018-09-11 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_remove_member_line_address'),
        ('purchase_order', '0015_purchaseorder_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_order_referal', to='membership.Member'),
        ),
    ]
