# Generated by Django 2.0.6 on 2018-09-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0017_auto_20180911_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
