# Generated by Django 2.0.8 on 2018-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0019_purchaseorderitem_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.PositiveIntegerField(help_text='Diskon Member', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.PositiveIntegerField(help_text='Ongkos Kirim', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_payment',
            field=models.PositiveIntegerField(help_text='Total Belanja', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_price',
            field=models.PositiveIntegerField(help_text='Total Belanja', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
