# Generated by Django 2.1.5 on 2019-02-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0020_auto_20181107_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='customer',
        ),
    ]
