# Generated by Django 2.0.6 on 2018-09-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_remove_member_line_address'),
        ('reward_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='my_poin',
            new_name='current_poin',
        ),
        migrations.AddField(
            model_name='reward',
            name='lifetime_poin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member'),
        ),
    ]
