# Generated by Django 2.0.6 on 2018-09-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0002_auto_20180911_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='current_poin',
            new_name='current_point',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='lifetime_poin',
            new_name='lifetime_point',
        ),
    ]
