# Generated by Django 2.0.6 on 2018-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0004_auto_20180911_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='lifetime_point',
        ),
        migrations.AddField(
            model_name='reward',
            name='current_selling',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
