# Generated by Django 2.0.6 on 2018-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0005_auto_20180911_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='bonus_selling',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
