# Generated by Django 2.0.6 on 2018-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0008_remove_reward_current_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='bonus_selling',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
