# Generated by Django 2.0.8 on 2018-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_system', '0009_reward_bonus_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='bonus_purchasing',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='bonus_selling',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='current_point',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
