# Generated by Django 2.0.6 on 2018-06-12 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_code', models.CharField(max_length=12)),
                ('home_address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Nomor Telepon Harus memiliki format +62819999999 atau 0819999999'. Maksimal 15 Digit.", regex='^\\+?62?\\d{9,15}$')])),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_sponsor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_code', models.CharField(max_length=12)),
                ('referal_code', models.CharField(max_length=12)),
                ('member_type', models.PositiveSmallIntegerField(choices=[(1, 'new member'), (2, 'dropshiper'), (3, 'reseller'), (4, 'agen'), (5, 'distributor'), (6, 'master seller')])),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Nomor Telepon Harus memiliki format +62819999999 atau 0819999999'. Maksimal 15 Digit.", regex='^\\+?62?\\d{9,15}$')])),
                ('ktp_address', models.CharField(max_length=250)),
                ('home_address', models.CharField(max_length=250)),
                ('ktp_number', models.IntegerField()),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_book_photo', models.ImageField(upload_to='bank_book_photo')),
                ('ktp_photo', models.ImageField(upload_to='ktp_photo')),
                ('profile_photo', models.ImageField(upload_to='profile_photo')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_sponsor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
