# Generated by Django 2.0.6 on 2018-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20180612_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bank_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ktp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'guest'), (1, 'new member'), (2, 'dropshiper'), (3, 'reseller'), (4, 'agen'), (5, 'distributor'), (6, 'master seller')], default=1),
        ),
    ]
