# Generated by Django 2.0.6 on 2018-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20180612_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qrcoce',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
