# Generated by Django 2.0.6 on 2018-06-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_member_qrcoce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='qrcoce',
            new_name='qrcode',
        ),
    ]
