# Generated by Django 2.0.6 on 2018-06-16 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20180615_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Guest'), (1, 'New Member'), (2, 'Dropshipper'), (3, 'Reseller'), (4, 'Agen'), (5, 'Distributor'), (6, 'Master Seller')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
