# Generated by Django 2.0.6 on 2018-07-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_remove_member_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='line_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='website_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
