# Generated by Django 2.0.6 on 2018-07-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20180710_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ktp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
