# Generated by Django 2.0.6 on 2018-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20180710_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='smart_motto',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
