# Generated by Django 2.0.6 on 2018-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20180721_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='home_kecamatan',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='home_kelurahan',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='home_kota',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='home_provinsi',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='ktp_kecamatan',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='ktp_kelurahan',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='ktp_kota',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='ktp_provinsi',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
