# Generated by Django 2.0.6 on 2018-09-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_remove_member_line_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line_address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
