# Generated by Django 2.0.6 on 2018-09-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_member_line_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='line_address',
        ),
    ]
