# Generated by Django 2.0.6 on 2018-09-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_remove_member_line_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('home_provinsi', models.CharField(blank=True, max_length=250)),
                ('home_kota', models.CharField(blank=True, max_length=250)),
                ('home_kecamatan', models.CharField(blank=True, max_length=250)),
                ('home_kelurahan', models.CharField(blank=True, max_length=250)),
                ('home_address', models.CharField(blank=True, max_length=250)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_customer', to='membership.Member')),
            ],
        ),
    ]
