# Generated by Django 2.0.8 on 2018-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_system', '0001_initial'),
        ('membership', '0023_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='used_voucher',
            field=models.ManyToManyField(help_text='Voucher yang dipakai member', related_name='voucher_used_by_member', to='voucher_system.Voucher'),
        ),
        migrations.AddField(
            model_name='member',
            name='wallet',
            field=models.PositiveIntegerField(default=0, help_text='Dompet Member', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_spent',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
