# Generated by Django 2.0.8 on 2018-11-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_auto_20181107_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
