# Generated by Django 2.0.8 on 2018-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_auto_20181113_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qrcode',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='member',
            name='used_voucher',
            field=models.ManyToManyField(blank=True, help_text='Voucher yang dipakai member', related_name='voucher_used_by_member', to='voucher_system.Voucher'),
        ),
    ]
