# Generated by Django 2.1.5 on 2019-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0017_remove_cart_customer'),
        ('purchase_order', '0021_remove_purchaseorder_customer'),
        ('membership', '0026_auto_20181113_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ktp_kecamatan',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ktp_kelurahan',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ktp_kota',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ktp_provinsi',
        ),
        migrations.RemoveField(
            model_name='member',
            name='referal_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='smart_motto',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sponsor_code',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], default=0),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
