# Generated by Django 2.0.8 on 2018-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
