# Generated by Django 2.0.6 on 2018-07-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_wilayah', '0002_auto_20180612_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=400, null=True)),
                ('kecamatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_wilayah.Kecamatan')),
                ('kelurahan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_wilayah.Kelurahan')),
                ('kota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_wilayah.Kota')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_wilayah.Provinsi')),
            ],
        ),
    ]
