# Generated by Django 2.0.6 on 2018-07-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingorigin',
            old_name='shipping_address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='shippingorigin',
            old_name='name',
            new_name='nama',
        ),
    ]
