# Generated by Django 2.0.6 on 2018-08-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_backend', '0003_auto_20180807_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorigin',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
