# Generated by Django 2.0.8 on 2018-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.SlugField(max_length=400)),
                ('addr2', models.SlugField(max_length=400)),
                ('banner2', models.ImageField(help_text='Banner 2', upload_to='home_settings')),
                ('addr3', models.SlugField(max_length=400)),
                ('banner3', models.ImageField(help_text='Banner 3', upload_to='home_settings')),
                ('addr4', models.SlugField(max_length=400)),
                ('banner1', models.ImageField(help_text='Banner 4', upload_to='home_settings')),
                ('addr5', models.SlugField(max_length=400)),
                ('banner5', models.ImageField(help_text='Banner 5', upload_to='home_settings')),
                ('addr_sidebar', models.SlugField(max_length=400)),
                ('banner_sidebar', models.ImageField(help_text='Banner Sidebar', upload_to='home_settings')),
                ('addr_middle', models.SlugField(max_length=400)),
                ('banner_middle', models.ImageField(help_text='Banner Middle', upload_to='home_settings')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.SlugField(max_length=400)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='headerlink',
            name='link',
            field=models.ManyToManyField(help_text='Link pada header', related_name='link_in_header', to='settings.Link'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link',
            field=models.ManyToManyField(help_text='Link pada footer', related_name='link_in_footer', to='settings.Link'),
        ),
    ]
