# Generated by Django 2.0.8 on 2018-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelink',
            name='addr1',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='addr3',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='addr4',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='addr5',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='banner1',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='banner2',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='banner3',
        ),
        migrations.RemoveField(
            model_name='homelink',
            name='banner5',
        ),
        migrations.AddField(
            model_name='homelink',
            name='addr_1',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AddField(
            model_name='homelink',
            name='addr_2',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AddField(
            model_name='homelink',
            name='addr_3',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AddField(
            model_name='homelink',
            name='addr_4',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AddField(
            model_name='homelink',
            name='addr_5',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AddField(
            model_name='homelink',
            name='banner_1',
            field=models.ImageField(help_text='Banner 1', null=True, upload_to='home_settings'),
        ),
        migrations.AddField(
            model_name='homelink',
            name='banner_2',
            field=models.ImageField(help_text='Banner 2', null=True, upload_to='home_settings'),
        ),
        migrations.AddField(
            model_name='homelink',
            name='banner_3',
            field=models.ImageField(help_text='Banner 3', null=True, upload_to='home_settings'),
        ),
        migrations.AddField(
            model_name='homelink',
            name='banner_4',
            field=models.ImageField(help_text='Banner 4', null=True, upload_to='home_settings'),
        ),
        migrations.AddField(
            model_name='homelink',
            name='banner_5',
            field=models.ImageField(help_text='Banner 5', null=True, upload_to='home_settings'),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_middle',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_sidebar',
            field=models.SlugField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='banner_middle',
            field=models.ImageField(help_text='Banner Middle', null=True, upload_to='home_settings'),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='banner_sidebar',
            field=models.ImageField(help_text='Banner Sidebar', null=True, upload_to='home_settings'),
        ),
    ]
