# Generated by Django 2.0.8 on 2018-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20181112_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelink',
            name='addr_1',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_2',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_3',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_4',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_5',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_middle',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='homelink',
            name='addr_sidebar',
            field=models.CharField(default='/', max_length=400),
        ),
        migrations.AlterField(
            model_name='link',
            name='addr',
            field=models.CharField(default='/', max_length=400),
        ),
    ]
