# Generated by Django 2.0.8 on 2018-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20181113_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='pos',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
