# Generated by Django 2.0.8 on 2018-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20181113_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='addr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='headerlink',
            name='addr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
