# Generated by Django 2.0.6 on 2018-09-03 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_member_total_spent'),
        ('database_wilayah', '0003_auto_20180808_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_dropship_addess', to='membership.Member')),
            ],
        ),
    ]
