# Generated by Django 2.0.6 on 2018-09-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_wilayah', '0004_dropshipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshipaddress',
            name='member',
        ),
        migrations.DeleteModel(
            name='DropshipAddress',
        ),
    ]
