# Generated by Django 2.0.6 on 2018-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product_photo')),
                ('price', models.IntegerField()),
                ('unit_weight', models.IntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='category', to='catalog.Category')),
            ],
        ),
    ]
