# Generated by Django 2.0.6 on 2018-06-09 21:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi Kategori'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Centang untuk Menyembunyikan Kategori'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nama Kategori', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Kategori Produk', related_name='category', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Deskripsi Produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Centang untuk Menyembunyikan Produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nama Produk', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='Foto Produk', upload_to='product_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Harga Produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(default=True, help_text='Centang Jika Produk Tersedia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.IntegerField(help_text='Berat Satuan Produk dalam gram'),
        ),
    ]
