# Generated by Django 2.0.6 on 2018-06-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180609_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_available',
            new_name='is_available',
        ),
    ]
