# Generated by Django 2.0.6 on 2018-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180611_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Harga Produk', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.IntegerField(help_text='Berat Satuan Produk dalam gram', null=True),
        ),
    ]
