# Generated by Django 2.0.6 on 2018-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Kategori Produk', related_name='products_in_category', to='catalog.Category'),
        ),
    ]
