# Generated by Django 2.0.6 on 2018-08-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180808_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
    ]
