# Generated by Django 2.0.8 on 2018-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poin',
            field=models.PositiveIntegerField(default=0, help_text='Poin Produk', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Harga Produk', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.PositiveIntegerField(help_text='Berat Satuan Produk dalam gram', null=True),
        ),
    ]
