# Generated by Django 2.0.8 on 2018-11-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20181107_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='poin',
            new_name='point',
        ),
    ]
