# Generated by Django 2.0.8 on 2018-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20181107_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(help_text='Ringkasan Produk', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Deskripsi Produk', null=True),
        ),
    ]
