# Generated by Django 2.0.8 on 2018-11-10 09:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20181110_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nama Brand', max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi Brand')),
                ('is_archived', models.BooleanField(default=False, help_text='Centang untuk Menyembunyikan Kategori')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(help_text='Brand Produk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_brand', to='catalog.Brand'),
        ),
    ]
