# Generated by Django 2.1.5 on 2019-02-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_auto_20181110_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nama Brand', max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi Brand')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default='', help_text='Merk Produk', max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(help_text='Toko Produk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_store', to='catalog.Store'),
        ),
    ]
