# Generated by Django 2.1.5 on 2019-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190208_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(help_text='Foto/Logo Toko', null=True, upload_to='store_photo'),
        ),
    ]
