# Generated by Django 2.1.5 on 2019-02-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190209_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Nama Kategori', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, help_text='Nama Brand', max_length=100, unique=True),
        ),
    ]
