# Generated by Django 2.1.5 on 2019-02-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20190210_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kota',
            field=models.ForeignKey(blank=True, help_text='Kota Produk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_city', to='database_wilayah.Kota'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provinsi',
            field=models.ForeignKey(blank=True, help_text='Provinsi Produk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_province', to='database_wilayah.Provinsi'),
        ),
    ]
