# Generated by Django 2.1.5 on 2019-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20190210_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baru'), (1, 'Bekas'), (2, 'Refurbished')], default=0),
        ),
    ]
