# Generated by Django 2.0.6 on 2018-07-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20180719_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCart',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shopping_cart.Cart')),
                ('anon_user', models.CharField(db_index=True, help_text='Nama Anon', max_length=200)),
            ],
            bases=('shopping_cart.cart',),
        ),
    ]
