# Generated by Django 2.0.6 on 2018-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_cart_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_service',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_sub_service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
