# Generated by Django 2.0.6 on 2018-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_auto_20180809_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
