# Generated by Django 2.0.6 on 2018-09-03 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0010_cart_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_referal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_referal', to=settings.AUTH_USER_MODEL),
        ),
    ]
