# Generated by Django 2.0.6 on 2018-09-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_auto_20180911_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_referal', to='membership.Member'),
        ),
    ]
